### ISSUE TITLE
How can i read the payload as ASCII or string?

### ISSUE THREAD

**Issue by melihyarikkaya** [melihyarikkaya/react-native-serialport#11]
How can i read the payload as ASCII or string?

_Originally posted by @ItaloSa in https://github.com/melihyarikkaya/react-native-serialport/issues/8#issuecomment-485412461_

**Comment by melihyarikkaya** [comment]
You need HEXSTRING or INTARRAY  convert to utf16 with `fromCharCode` when  after readed.

_if your returned data type is `INTARRAY`_
```javascript
onReadData(data) {
  let intArray = data.payload;
  let str = "";
  let radix = 10;
  for (var i = 0; i < intArray.length && intArray.substr(i, 2) !== "00"; i += 2) {
    str += String.fromCharCode(parseInt(intArray.substr(i, 2), radix));
  }

  console.log(str);
}
```
_or `HEXSTRING`_

```javascript
onReadData(data) {
 let hex = data.payload;
  let str = "";
  let radix = 16;
  for (var i = 0; i < hex.length && hex.substr(i, 2) !== "00"; i += 2) {
    str += String.fromCharCode(parseInt(hex.substr(i, 2), radix));
  }
  console.log(str);
}
```

**Comment by melihyarikkaya** [comment]
@ItaloSa Did this answer help you?

**Comment by ItaloSa** [comment]
That is helping me a lot! I'm using it on my research in Systems and Networks of Internet class. I'm looking to read serial data from NODEMCU that's sniffing probe requests. Thanks a lot.
