### ISSUE TITLE
Reading serial data

### ISSUE THREAD

**Issue by to0ney** [melihyarikkaya/react-native-serialport#2]
When I receive data from the event 'onReadDataFromPort', how can I format as a readable UTF-8 string?  I believe its currently being passed as hex chars.

Thanks for the great contribution!

**Comment by melihyarikkaya** [comment]
I hope it works for you. 
Worked for me

> onConnectedDevice() { 
>     RNSerialport.writeString("HELLO");
>    }
> 
>  onReadData(data) {
>     let str = "";
>     let characterCount = data.length;
>     for(let i = 0; i< characterCount; i+=2) {
>       str += String.fromCharCode(parseInt(data.substr(i, 2), 10));
>     }
>     alert(str) //string
>   }


I tested it with Arduino
My arduino code

> void setup() {
> 
> Serial.begin(9600);
> }
> void loop() 
> {
>   if(Serial.available())
>     {
>       String k = Serial.readString();
>       if(k == "HELLO")
>         Serial.write("Hello World");
>     }
>     
> }
