### ISSUE TITLE
overrideLibrary address in manifest.xml

### ISSUE THREAD

**Issue by iozeen** [melihyarikkaya/react-native-serialport#3]
Hi. I'm using your library and it's working as intended. But since I can't use it on lower versions of android I would like to override it in manifest file just to ignore apk installation error. Wanted to know address of library to put in here:` tools:overrideLibrary="com.reactlibrary"`

**Comment by melihyarikkaya** [comment]
If you give me some more details, I will do my best to help you. In my manifest file, the package is written as "com.reactlibrary". I didn't think I'd fix that.

**Comment by iozeen** [comment]
Thanks for reply. I've used your library to create connection with scales (work app). It supports 6+ android versions. I wanted to support version 5 but I need to ignore scales functionality. Here's what it said after I tried to generate Signed APK:
```
Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 23 declared in library [:react-native-serialport] /home/zinkevych/Projects/ee-biomauris/app/node_modules/react-native-serialport/android/build/intermediates/manifests/full/release/AndroidManifest.xml as the library might be using APIs not available in 19
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="com.reactlibrary" to force usage (may lead to runtime failures)
```
Yeah, it says "com.reactlibrary" but it sounds like an example snippet. I've tried "com.melihyarikkaya.react-native-serialport" but sounds like no effect.

**Comment by iozeen** [comment]
@melihyarikkaya my bad. 
**BUILD SUCCESSFUL in 33s** with "com.reactlibrary". Gonna test how its installing on phone.  Thanks

**Comment by melihyarikkaya** [comment]
I checked. I realized I made a mistake. The package name is "com.reactlibrary". Tomorrow I will correct this and publish a version. Thank you for reporting this.
